[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Extensions.pdo", "php82Extensions.mbstring", "php82Extensions.tokenizer", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.fileinfo", "php82Extensions.bcmath"]

[phases.build]
cmds = [
  "composer install --no-dev",
  "php artisan config:cache",
  "php artisan migrate --force"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
